
server:
  port: 8081
  
spring:
 # Definindo nome da aplicação mostrada no eureka   
  application:
    name: 'fornecedor'

# Configuração para o Eureka Client para se registrar no Eureka Server 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka  